apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: django-blog
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: django-blog
        static_configs:
          - targets:
              - django-blog.django-blog.svc.cluster.local:80
